/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Nativeid = string | null;
export type Name = string | null;
export type Color = string;
export type Number = number;
/**
 * Visual states for agent characters.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "AgentState".
 */
export type AgentState =
  | "arriving"
  | "reporting"
  | "walking_to_desk"
  | "working"
  | "thinking"
  | "waiting_permission"
  | "completed"
  | "waiting"
  | "reporting_done"
  | "leaving"
  | "in_elevator";
export type Desk = number | null;
/**
 * Type of speech/thought bubble content.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "BubbleType".
 */
export type BubbleType = "thought" | "speech";
export type Text = string;
export type Icon = string | null;
export type Persistent = boolean;
export type Currenttask = string | null;
export type Agentid = string;
export type Agentname = string;
export type Color1 = string;
export type Starttime = string;
export type Endtime = string | null;
export type Taskid = string;
export type Status = string;
export type Summary = string | null;
export type Startedat = string | null;
export type Completedat = string | null;
/**
 * Visual states for the boss character.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "BossState".
 */
export type BossState =
  | "idle"
  | "phone_ringing"
  | "on_phone"
  | "receiving"
  | "working"
  | "delegating"
  | "waiting_permission"
  | "reviewing"
  | "completing";
export type Currenttask1 = string | null;
export type Path = string;
/**
 * Git file status codes.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "FileStatus".
 */
export type FileStatus = "M" | "A" | "D" | "R" | "C" | "?" | "!";
export type Staged = boolean;
/**
 * Short commit hash (7 chars)
 */
export type Hash = string;
/**
 * First line of commit message
 */
export type Message = string;
export type Author = string;
export type Timestamp = string;
/**
 * Human-readable relative time (e.g., '2 hours ago')
 */
export type RelativeTime = string;
export type Id1 = string;
export type Role = string;
export type Agentid1 = string;
export type Text1 = string;
export type Timestamp1 = string;
export type Toolname = string;
/**
 * Visual states for the elevator.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "ElevatorState".
 */
export type ElevatorState = "closed" | "arriving" | "open" | "departing";
/**
 * Types of events sent from Claude Code hooks.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "EventType".
 */
export type EventType =
  | "session_start"
  | "session_end"
  | "pre_tool_use"
  | "post_tool_use"
  | "user_prompt_submit"
  | "permission_request"
  | "notification"
  | "subagent_start"
  | "subagent_info"
  | "subagent_stop"
  | "agent_update"
  | "stop"
  | "cleanup"
  | "context_compaction"
  | "reporting"
  | "walking_to_desk"
  | "waiting"
  | "leaving"
  | "error"
  | "background_task_notification";
export type SessionId = string;
export type Timestamp2 = string;
export type ProjectName = string | null;
export type ProjectDir = string | null;
export type WorkingDir = string | null;
export type ToolName = string | null;
export type ToolUseId = string | null;
export type ToolInput = {
  [k: string]: unknown;
} | null;
export type Success = boolean | null;
export type AgentId = string | null;
export type NativeAgentId = string | null;
export type AgentName = string | null;
export type AgentType = string | null;
export type TaskDescription = string | null;
export type ResultSummary = string | null;
export type NotificationType = string | null;
export type Message1 = string | null;
export type ErrorType = string | null;
export type Reason = string | null;
export type Summary1 = string | null;
export type Prompt = string | null;
export type Boss1 = string | null;
export type Agent1 = string | null;
export type BossPhone = string | null;
export type TranscriptPath = string | null;
export type AgentTranscriptPath = string | null;
export type Thinking = string | null;
export type InputTokens = number | null;
export type OutputTokens = number | null;
export type CacheReadTokens = number | null;
export type CacheCreationTokens = number | null;
export type BackgroundTaskId = string | null;
export type BackgroundTaskOutputFile = string | null;
export type BackgroundTaskStatus = string | null;
export type BackgroundTaskSummary = string | null;
export type TaskListId = string | null;
export type Filepath = string;
export type Editcount = number;
export type Sessionid = string;
export type Agents = Agent[];
export type Deskcount = number;
/**
 * Visual states for the elevator.
 */
export type ElevatorState1 = "closed" | "arriving" | "open" | "departing";
/**
 * Visual states for the boss's phone.
 */
export type PhoneState = "idle" | "ringing" | "in_use";
export type Contextutilization = number;
export type Toolusessincecompaction = number;
export type Printreport = boolean;
export type Lastupdated = string;
export type Id2 = string;
export type Type = string;
export type Agentid2 = string;
export type Summary2 = string;
export type Timestamp3 = string;
export type History = HistoryEntry[];
export type TaskId = string;
export type Content = string;
/**
 * Status of a todo list item.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "TodoStatus".
 */
export type TodoStatus = "pending" | "in_progress" | "completed";
export type ActiveForm = string | null;
export type Description = string | null;
export type Blocks = string[];
export type BlockedBy = string[];
export type Owner = string | null;
export type Metadata = {
  [k: string]: unknown;
} | null;
export type Todos = TodoItem[];
export type Arrivalqueue = string[];
export type Departurequeue = string[];
export type Taskcompletedcount = number;
export type Bugfixedcount = number;
export type Coffeebreakcount = number;
export type Codewrittencount = number;
export type Recenterrorcount = number;
export type Recentsuccesscount = number;
export type Activitylevel = number;
export type Consecutivesuccesses = number;
export type Lastincidenttime = string | null;
export type Agentlifespans = AgentLifespan[];
export type Category = string;
export type Headline = string;
export type Timestamp4 = string;
export type Newsitems = NewsItem[];
export type Coffeecups = number;
export type Backgroundtasks = BackgroundTask[];
export type Conversation = ConversationEntry[];
/**
 * Current branch name
 */
export type Branch = string;
/**
 * Commits ahead of remote
 */
export type Ahead = number;
/**
 * Commits behind remote
 */
export type Behind = number;
export type ChangedFiles = ChangedFile[];
/**
 * Last 10 commits
 */
export type Commits = Commit[];
export type LastUpdated = string;
/**
 * Path to the repository
 */
export type RepoPath = string;
/**
 * Visual states for the boss's phone.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "PhoneState".
 */
export type PhoneState1 = "idle" | "ringing" | "in_use";
export type Id3 = string;
export type CreatedAt = string;
export type UpdatedAt = string;
export type Status1 = string;
export type EventCount = number;
export type AgentCount = number;

export interface ClaudeOfficeBackendTypes {
  [k: string]: unknown;
}
/**
 * Represents a subagent in the office visualization.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "Agent".
 */
export interface Agent {
  id: Id;
  nativeId?: Nativeid;
  agentType?: string;  // "main" or "subagent"
  name?: Name;
  color: Color;
  number: Number;
  state: AgentState;
  desk?: Desk;
  bubble?: BubbleContent | null;
  currentTask?: Currenttask;
  position?: Position;
  [k: string]: unknown;
}
/**
 * Content for speech or thought bubbles.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "BubbleContent".
 */
export interface BubbleContent {
  type: BubbleType;
  text: Text;
  icon?: Icon;
  persistent?: Persistent;
  [k: string]: unknown;
}
export interface Position {
  [k: string]: number;
}
/**
 * Timeline entry for agent lifespan tracking.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "AgentLifespan".
 */
export interface AgentLifespan {
  agentId: Agentid;
  agentName: Agentname;
  color: Color1;
  startTime: Starttime;
  endTime?: Endtime;
  [k: string]: unknown;
}
/**
 * Background task tracking for remote workers display.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "BackgroundTask".
 */
export interface BackgroundTask {
  taskId: Taskid;
  status: Status;
  summary?: Summary;
  startedAt?: Startedat;
  completedAt?: Completedat;
  [k: string]: unknown;
}
/**
 * Represents the main Claude agent (boss) in the office visualization.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "Boss".
 */
export interface Boss {
  state: BossState;
  currentTask?: Currenttask1;
  bubble?: BubbleContent | null;
  position?: Position1;
  [k: string]: unknown;
}
export interface Position1 {
  [k: string]: number;
}
/**
 * A file with changes in the working tree or index.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "ChangedFile".
 */
export interface ChangedFile {
  path: Path;
  status: FileStatus;
  staged?: Staged;
  [k: string]: unknown;
}
/**
 * A git commit summary.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "Commit".
 */
export interface Commit {
  hash: Hash;
  message: Message;
  author: Author;
  timestamp: Timestamp;
  relative_time: RelativeTime;
  [k: string]: unknown;
}
/**
 * A single turn in the conversation history.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "ConversationEntry".
 */
export interface ConversationEntry {
  id: Id1;
  role: Role;
  agentId: Agentid1;
  text: Text1;
  timestamp: Timestamp1;
  toolName?: Toolname;
  [k: string]: unknown;
}
/**
 * An event from Claude Code hooks.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  event_type: EventType;
  session_id: SessionId;
  timestamp?: Timestamp2;
  data: EventData;
  [k: string]: unknown;
}
/**
 * Data payload for events from Claude Code hooks.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "EventData".
 */
export interface EventData {
  project_name?: ProjectName;
  project_dir?: ProjectDir;
  working_dir?: WorkingDir;
  tool_name?: ToolName;
  tool_use_id?: ToolUseId;
  tool_input?: ToolInput;
  success?: Success;
  agent_id?: AgentId;
  native_agent_id?: NativeAgentId;
  agent_name?: AgentName;
  agent_type?: AgentType;
  task_description?: TaskDescription;
  result_summary?: ResultSummary;
  notification_type?: NotificationType;
  message?: Message1;
  error_type?: ErrorType;
  reason?: Reason;
  summary?: Summary1;
  prompt?: Prompt;
  bubble_content?: BubbleContent | null;
  speech_content?: SpeechContent | null;
  transcript_path?: TranscriptPath;
  agent_transcript_path?: AgentTranscriptPath;
  thinking?: Thinking;
  input_tokens?: InputTokens;
  output_tokens?: OutputTokens;
  cache_read_tokens?: CacheReadTokens;
  cache_creation_tokens?: CacheCreationTokens;
  background_task_id?: BackgroundTaskId;
  background_task_output_file?: BackgroundTaskOutputFile;
  background_task_status?: BackgroundTaskStatus;
  background_task_summary?: BackgroundTaskSummary;
  task_list_id?: TaskListId;
  [k: string]: unknown;
}
/**
 * Speech content for different characters.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "SpeechContent".
 */
export interface SpeechContent {
  boss?: Boss1;
  agent?: Agent1;
  boss_phone?: BossPhone;
  [k: string]: unknown;
}
/**
 * File edit tracking for heat map display.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "FileEdit".
 */
export interface FileEdit {
  filePath: Filepath;
  editCount: Editcount;
  [k: string]: unknown;
}
/**
 * Complete state of the office visualization for frontend rendering.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "GameState".
 */
export interface GameState {
  sessionId: Sessionid;
  boss: Boss;
  agents: Agents;
  office: OfficeState;
  lastUpdated: Lastupdated;
  history?: History;
  todos?: Todos;
  arrivalQueue?: Arrivalqueue;
  departureQueue?: Departurequeue;
  whiteboardData?: WhiteboardData;
  conversation?: Conversation;
  [k: string]: unknown;
}
/**
 * Represents the overall state of the office environment.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "OfficeState".
 */
export interface OfficeState {
  deskCount?: Deskcount;
  elevatorState?: ElevatorState1;
  phoneState?: PhoneState;
  contextUtilization?: Contextutilization;
  toolUsesSinceCompaction?: Toolusessincecompaction;
  printReport?: Printreport;
  [k: string]: unknown;
}
/**
 * A single entry in the event history log.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "HistoryEntry".
 */
export interface HistoryEntry {
  id: Id2;
  type: Type;
  agentId: Agentid2;
  summary: Summary2;
  timestamp: Timestamp3;
  detail: Detail;
  [k: string]: unknown;
}
export interface Detail {
  [k: string]: unknown;
}
/**
 * A single item from the TodoWrite tool or task file system.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "TodoItem".
 */
export interface TodoItem {
  task_id?: TaskId;
  content: Content;
  status: TodoStatus;
  active_form?: ActiveForm;
  description?: Description;
  blocks?: Blocks;
  blocked_by?: BlockedBy;
  owner?: Owner;
  metadata?: Metadata;
  [k: string]: unknown;
}
/**
 * Data for whiteboard display modes.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "WhiteboardData".
 */
export interface WhiteboardData {
  toolUsage?: Toolusage;
  taskCompletedCount?: Taskcompletedcount;
  bugFixedCount?: Bugfixedcount;
  coffeeBreakCount?: Coffeebreakcount;
  codeWrittenCount?: Codewrittencount;
  recentErrorCount?: Recenterrorcount;
  recentSuccessCount?: Recentsuccesscount;
  activityLevel?: Activitylevel;
  consecutiveSuccesses?: Consecutivesuccesses;
  lastIncidentTime?: Lastincidenttime;
  agentLifespans?: Agentlifespans;
  newsItems?: Newsitems;
  coffeeCups?: Coffeecups;
  fileEdits?: Fileedits;
  backgroundTasks?: Backgroundtasks;
  [k: string]: unknown;
}
export interface Toolusage {
  [k: string]: number;
}
/**
 * News ticker item for the whiteboard.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "NewsItem".
 */
export interface NewsItem {
  category: Category;
  headline: Headline;
  timestamp: Timestamp4;
  [k: string]: unknown;
}
export interface Fileedits {
  [k: string]: number;
}
/**
 * Current git repository status.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "GitStatus".
 */
export interface GitStatus {
  branch: Branch;
  ahead?: Ahead;
  behind?: Behind;
  changed_files?: ChangedFiles;
  commits?: Commits;
  last_updated?: LastUpdated;
  repo_path: RepoPath;
  [k: string]: unknown;
}
/**
 * A Claude Code session summary.
 *
 * This interface was referenced by `ClaudeOfficeBackendTypes`'s JSON-Schema
 * via the `definition` "Session".
 */
export interface Session {
  id: Id3;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  status: Status1;
  event_count: EventCount;
  agent_count: AgentCount;
  [k: string]: unknown;
}
